# ===============================
# POSTGRESQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/sangabriel_db_rrhh
spring.datasource.username=postgres
spring.datasource.password=jenner0125
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# FLYWAY
# ===============================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# ===============================
# HIBERNATE / JPA
# ===============================

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# ===============================
# SERVER
# ===============================

server.port=8080


# ===============================
# JWT (OPCIONAL POR AHORA)
# ===============================

jwt.expiration=900000