/* PRIMER ESTRUCTURA DE BASE DE DATOS PARA EL HOSPITAL SAN GABRIEL */

CREATE TABLE rol (
    id_rol SERIAL PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE departamento(
    id_dpto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR (100) NOT NULL,
    cod_dpto VARCHAR (20) UNIQUE ,
    ubicacion VARCHAR (100),
    jefe_dpto BIGINT ,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE empleado(
    id_empleado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR (100) NOT NULL,
    apellidos VARCHAR (100) NOT NULL,
    doc_identidad VARCHAR (15) NOT NULL DEFAULT 'DNI' CHECK (doc_identidad IN('DNI','CE')),
    numero_di VARCHAR (15) UNIQUE NOT NULL,
    fecha_nac DATE NOT NULL,
    sexo VARCHAR(1) NOT NULL CHECK (sexo IN ('F', 'M')),
    estado_civil VARCHAR(20) DEFAULT 'SOLTERO' CHECK (estado_civil IN ('SOLTERO', 'CASADO', 'DIVORCIADO', 'VIUDO', 'CONVIVIENTE')),
    direccion VARCHAR (80) NOT NULL ,
    correo VARCHAR (50) NOT NULL,
    telefono VARCHAR (15),
    estado VARCHAR (30) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN('ACTIVO','LICENCIA','SUSPENDIDO','DESVINCULADO')),
    huella_template TEXT,
    saldo_vacaciones INT DEFAULT 30,
    creado_el TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_desvinculacion TIMESTAMP
);

ALTER TABLE departamento ADD CONSTRAINT fk_jefe_dpto FOREIGN KEY (jefe_dpto) REFERENCES empleado(id_empleado);

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) UNIQUE NOT NULL,
    correo_inst VARCHAR (50) UNIQUE NOT NULL,
    contrasenia VARCHAR(255) NOT NULL,
    id_empleado BIGINT UNIQUE REFERENCES empleado(id_empleado),
    id_rol INT REFERENCES rol(id_rol),
    intentos_fallidos INT DEFAULT 0,
    cuenta_bloqueada BOOLEAN DEFAULT FALSE,
    fecha_bloqueo TIMESTAMP,
    dosfa_activo BOOLEAN DEFAULT FALSE,
    dosfa_secret VARCHAR (255),
    intentos_falla_2fa INT DEFAULT 0,
    bloqueo_2fa_hasta TIMESTAMP NULL,
    token_invalido_desde TIMESTAMP NULL,
    activo BOOLEAN DEFAULT TRUE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contrato (
    id_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo VARCHAR(100) NOT NULL,
    tipo_contrato VARCHAR(50) NOT NULL CHECK (tipo_contrato IN ('PLAZO FIJO', 'INDEFINIDO', 'POR OBRA', 'PRACTICAS')),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    sueldo DECIMAL(10,2) NOT NULL,
    tipo_pension VARCHAR(10) DEFAULT 'ONP' CHECK (tipo_pension IN ('ONP', 'AFP')),
    estado VARCHAR(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'VENCIDO', 'RESUELTO', 'SUSPENDIDO')),
    id_empleado BIGINT NOT NULL REFERENCES empleado(id_empleado),
    id_dpto INT NOT NULL REFERENCES departamento(id_dpto),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE familia_info (
    id_familia_info SERIAL PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    parentesco VARCHAR(50) NOT NULL CHECK (parentesco IN ('HIJO', 'CONYUGE', 'PADRE', 'MADRE', 'HERMANO')),
    numero_di VARCHAR(15) UNIQUE,
    fecha_nacimiento DATE NOT NULL,
    id_empleado BIGINT REFERENCES empleado(id_empleado),
    activo BOOLEAN DEFAULT TRUE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE empleado_derecho_habientes (
    id_emp_dh BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regimen_salud VARCHAR(100),
    regimen_pension VARCHAR(100),
    contacto_emergencia VARCHAR(100),
    telefono_emergencia VARCHAR(15),
    id_empleado BIGINT UNIQUE REFERENCES empleado(id_empleado),
    activo BOOLEAN DEFAULT TRUE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE horario (
    id_horario SERIAL PRIMARY KEY,
    nombre_turno VARCHAR(50) NOT NULL,
    hora_entrada TIME NOT NULL,
    hora_salida TIME NOT NULL,
    tolerancia INT DEFAULT 10,
    umbral_extra INT DEFAULT 60,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE sancion(
    id_sancion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado BIGINT NOT NULL REFERENCES empleado(id_empleado),
    codigo VARCHAR(30) UNIQUE,
    motivo VARCHAR(150) NOT NULL,
    descripcion TEXT,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    bloquea_acceso BOOLEAN DEFAULT FALSE,
    estado VARCHAR(20) DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA', 'FINALIZADA', 'ANULADA')),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reseteo_contrasenia (
    id_token BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario),
    expiracion TIMESTAMP NOT NULL,
    usado BOOLEAN DEFAULT FALSE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE registro_asistencia (
    id_registro SERIAL PRIMARY KEY,
    fecha DATE DEFAULT CURRENT_DATE,
    hora_entrada TIME,
    hora_salida TIME,
    minutos_tardanza INT DEFAULT 0,
    minutos_extra INT DEFAULT 0,
    horas_trabajadas DECIMAL(10,2) DEFAULT 0,
    tipo_ultimo_registro VARCHAR(20),
    tipo_registro VARCHAR(20) DEFAULT 'ORIGINAL',
    observacion VARCHAR(255),
    estado VARCHAR(30),
    id_empleado BIGINT REFERENCES empleado(id_empleado),
    id_horario BIGINT REFERENCES horario(id_horario),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE nomina (
    id_nomina SERIAL PRIMARY KEY,
    periodo VARCHAR(20) NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    fecha_emision DATE DEFAULT CURRENT_DATE,
    sueldo_base DECIMAL(10,2),
    total_horas_trabajadas DECIMAL(10,2) DEFAULT 0,
    total_horas_extra DECIMAL(10,2) DEFAULT 0,
    total_minutos_tardanza INT DEFAULT 0,
    bonif_familiar DECIMAL(10,2) DEFAULT 0,
    bonif_turno_nocturno DECIMAL(10,2) DEFAULT 0,
    bonif_guardia DECIMAL(10,2) DEFAULT 0,
    bonif_riesgo DECIMAL(10,2) DEFAULT 0,
    bonif_cargo DECIMAL(10,2) DEFAULT 0,
    descuento_tardanzas DECIMAL(10,2) DEFAULT 0,
    descuento_ley DECIMAL(10,2) DEFAULT 0,
    asignacion_familiar DECIMAL(10,2) DEFAULT 0,
    sueldo_bruto DECIMAL(10,2) DEFAULT 0,
    sueldo_neto DECIMAL(10,2) NOT NULL,
    cantidad_hijos INT DEFAULT 0,
    tiene_hijos BOOLEAN DEFAULT FALSE,
    cantidad_guardias INT DEFAULT 0,
    total_horas_nocturnas DECIMAL(6,2) DEFAULT 0,
    tipo_pension_aplicada VARCHAR(10) DEFAULT 'ONP',
    estado_pago VARCHAR(20) DEFAULT 'PENDIENTE' CHECK (estado_pago IN ('PENDIENTE','CALCULADA','DISPONIBLE','PAGADA')),
    version INT DEFAULT 1,
    nomina_anterior_id INT NULL,
    id_empleado BIGINT REFERENCES empleado(id_empleado),
    calculado_por BIGINT REFERENCES usuario(id_usuario),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE detalle_nomina (
    id_detalle SERIAL PRIMARY KEY,
    id_nomina INT NOT NULL REFERENCES nomina(id_nomina) ON DELETE CASCADE,
    id_empleado BIGINT NOT NULL REFERENCES empleado(id_empleado),
    fecha DATE NOT NULL,
    horas_trabajadas DECIMAL(8,2) DEFAULT 0,
    minutos_tardanza INT DEFAULT 0,
    minutos_extra INT DEFAULT 0,
    monto_hora_extra DECIMAL(10,2) DEFAULT 0,
    descuento_tardanza DECIMAL(10,2) DEFAULT 0,
    observacion VARCHAR(255),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE solicitud (
    id_solicitud SERIAL PRIMARY KEY,
    tipo_solicitud VARCHAR(50) NOT NULL CHECK (tipo_solicitud IN ('VACACIONES', 'PERMISO_PERSONAL', 'PERMISO_MEDICO', 'OTROS')),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    dias_solicitados INT DEFAULT 0,
    motivo TEXT NOT NULL,
    estado VARCHAR(20) DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'OBSERVADO', 'PROCESADO', 'APROBADA', 'RECHAZADA')),
    respuesta TEXT,
    observacion_rrhh TEXT,
    archivo_adjunto VARCHAR(255),
    id_empleado BIGINT REFERENCES empleado(id_empleado),
    revisado_por BIGINT REFERENCES usuario(id_usuario),
    aprobado_por BIGINT REFERENCES usuario(id_usuario),
    fecha_revision TIMESTAMP,
    fecha_decision TIMESTAMP,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE historial_auditoria (
    id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT REFERENCES usuario(id_usuario),
    tabla_afectada VARCHAR(50) NOT NULL,
    id_registro_afectado BIGINT NOT NULL,
    accion VARCHAR(70) NOT NULL,
    valor_anterior TEXT,
    valor_nuevo TEXT,
    ip_maquina VARCHAR(45),
    fecha_de_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE asignacion_horario (
    id_asignacion SERIAL PRIMARY KEY,
    id_empleado BIGINT NOT NULL REFERENCES empleado(id_empleado),
    id_horario INT NOT NULL REFERENCES horario(id_horario),
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE,
    es_temporal BOOLEAN DEFAULT FALSE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE reporte_generado (
    id_reporte SERIAL PRIMARY KEY,
    tipo_reporte VARCHAR(50) NOT NULL CHECK (tipo_reporte IN ('EMPLEADOS', 'ASISTENCIA', 'NOMINA', 'SOLICITUDES')),
    filtros_aplicados TEXT,
    total_registros INT DEFAULT 0,
    formato_exportacion VARCHAR(10),
    generado_por BIGINT REFERENCES usuario(id_usuario),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE justificacion_tardanza (
    id_justificacion SERIAL PRIMARY KEY,
    id_registro_asistencia INTEGER NOT NULL REFERENCES registro_asistencia(id_registro),
    id_empleado BIGINT NOT NULL REFERENCES empleado(id_empleado),
    motivo VARCHAR(500) NOT NULL,
    evidencia_url VARCHAR(500),
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_justificacion TIMESTAMP NOT NULL DEFAULT NOW(),
    revisado_por BIGINT REFERENCES usuario(id_usuario),
    fecha_revision TIMESTAMP,
    comentario_revision VARCHAR(500)
);

CREATE TABLE notificacion_envio (
    id_notificacion SERIAL PRIMARY KEY,
    id_nomina INT NOT NULL REFERENCES nomina(id_nomina),
    tipo VARCHAR(30) NOT NULL DEFAULT 'COMPROBANTE_NOMINA',
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    intentos INT DEFAULT 0,
    max_intentos INT DEFAULT 3,
    fecha_envio TIMESTAMP,
    error TEXT,
    creado_el TIMESTAMP DEFAULT NOW()
);

CREATE TABLE feriado (
    id_feriado SERIAL PRIMARY KEY,
    fecha DATE NOT NULL UNIQUE,
    descripcion VARCHAR(100)
);

-- =========================
-- INDICES
-- =========================

CREATE INDEX idx_empleado_dni ON empleado(numero_di);
CREATE INDEX idx_empleado_nombres ON empleado(nombres, apellidos);
CREATE INDEX idx_empleado_estado ON empleado(estado);
CREATE INDEX idx_usuario_login ON usuario(nombre_usuario) WHERE activo = TRUE;
CREATE INDEX idx_asistencia_emp_fecha ON registro_asistencia(id_empleado, fecha);
CREATE INDEX idx_asignacion_vigente ON asignacion_horario(id_empleado, fecha_desde, fecha_hasta) WHERE activo = TRUE;
CREATE INDEX idx_contrato_cargo ON contrato(cargo);
CREATE INDEX idx_contrato_emp_estado ON contrato(id_empleado, estado);

-- =========================
-- TRIGGERS
-- =========================

CREATE OR REPLACE FUNCTION fn_calcular_tardanza()
RETURNS TRIGGER AS $$
DECLARE
    v_id_horario INT;
    v_h_esperada TIME;
    v_tolerancia INT;
BEGIN
    SELECT id_horario INTO v_id_horario FROM asignacion_horario
    WHERE id_empleado = NEW.id_empleado AND NEW.fecha BETWEEN fecha_desde AND fecha_hasta AND activo = TRUE LIMIT 1;
    IF v_id_horario IS NULL THEN RETURN NEW; END IF;
    SELECT hora_entrada, tolerancia INTO v_h_esperada, v_tolerancia FROM horario WHERE id_horario = v_id_horario;
    IF NEW.hora_entrada > (v_h_esperada + (v_tolerancia || ' minutes')::interval) THEN
        NEW.minutos_tardanza := EXTRACT(EPOCH FROM (NEW.hora_entrada - v_h_esperada)) / 60;
    ELSE
        NEW.minutos_tardanza := 0;
    END IF;
    NEW.id_horario := v_id_horario;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_entrada_asistencia BEFORE INSERT ON registro_asistencia
FOR EACH ROW EXECUTE FUNCTION fn_calcular_tardanza();

CREATE OR REPLACE FUNCTION fn_calcular_extras()
RETURNS TRIGGER AS $$
DECLARE
    v_h_salida_esperada TIME;
    v_umbral INT;
    v_minutos_reales INT;
BEGIN
    IF NEW.hora_salida IS NULL THEN RETURN NEW; END IF;
    SELECT hora_salida, umbral_extra INTO v_h_salida_esperada, v_umbral FROM horario WHERE id_horario = NEW.id_horario;
    v_minutos_reales := EXTRACT(EPOCH FROM (NEW.hora_salida - v_h_salida_esperada)) / 60;
    IF v_minutos_reales >= v_umbral THEN
        NEW.minutos_extra := v_minutos_reales;
    ELSE
        NEW.minutos_extra := 0;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_salida_asistencia BEFORE UPDATE OF hora_salida ON registro_asistencia
FOR EACH ROW EXECUTE FUNCTION fn_calcular_extras();

CREATE OR REPLACE FUNCTION fn_timestamp_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.actualizado_el = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_act_empleado BEFORE UPDATE ON empleado FOR EACH ROW EXECUTE FUNCTION fn_timestamp_update();
CREATE TRIGGER tr_act_contrato BEFORE UPDATE ON contrato FOR EACH ROW EXECUTE FUNCTION fn_timestamp_update();
CREATE TRIGGER tr_act_usuario BEFORE UPDATE ON usuario FOR EACH ROW EXECUTE FUNCTION fn_timestamp_update();
